app/Http/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*Route::get('/design/pattern', function () {
	$redDuck = new App\Acme\Duck\RedHeadDuck();
	$RubberDuck = new App\Acme\Duck\RubberDuck();

	// it can quack
	echo (($redDuck->performFly()));
	echo '</br>';
	// it can not fly
	echo ($redDuck->performQuack());
	echo '</br>';

	// it can not fly
	echo (($RubberDuck->performFly()));
	echo '</br>';
	// it can quack
	echo ($RubberDuck->performQuack());
});*/




Route::group(['middleware' => 'auth'], function() {

	Route::get('/{home?}', ['as'=>'home', 'uses'=>'MeetingController@index']);
	Route::get('auth/logout',['as'=>'auth.logout','uses'=>'Auth\AuthController@getLogout']);
	Route::resource('meeting','MeetingController');
	Route::get('/meeting/show/{id}','MeetingController@getShowMeeting');


});

Route::group(['middleware'=>'guest'], function () {

	Route::get('/auth/login','Auth\AuthController@getLogin');
	Route::post('/auth/login','Auth\AuthController@postLogin');
	Route::get('auth/register',['as'=>'auth.register','uses'=>'Auth\AuthController@getRegister']);
	Route::post('auth/register','Auth\AuthController@postRegister');

});






//Route::get('/login',['as'=>'login.auth','uses'=>'AuthController']);

/*Route::get('home', 'HomeController@index');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);*/

app/Meeting.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Meeting extends Model {

	//
    protected $table ='meetings';
    protected $fillable = [
        'subject',
        'description',
        'date',
        'time',
        'user_id'
    ];

    // a meeting belongs to one user
    public function users () {
        return $this->belongsToMany('User');
    }

}

app/Http/Controllers/MeetingController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests\CreateMeetingRequest;
use App\Acme\Meetings\MeetingRepository;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;

class MeetingController extends Controller {


	public $meeting;
	public $attendees;
	public function __construct(MeetingRepository $model, User $user) {
		$this->meeting = $model;
		$this->user = $user;
	}

    /*
		Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//

		$allMeetings = $this->meeting->model->orderBy('created_at','desc')->paginate(6);
		return View('site.meetings.index', compact('allMeetings'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */

	public function create()
	{
		//
		$allAttendees = DB::table('users')->lists('name','id');
		return View('site.meetings.create',compact('allAttendees'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(CreateMeetingRequest $request)
	{
		//
		$createdMeeting = $this->meeting->model->create($request->all());
		if($createdMeeting) {
			foreach ($request->get('attendees') as $attendee) {
				DB::table('meeting_user')->insert(['user_id'=> $attendee, 'meeting_id' => $createdMeeting->id]);
			}
		return redirect(route('home'))->with('message',' Meeting created successfully .. thank you');
		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//

		// all meetings that is related to one user
		$allMeetings =  $this->user->find($id)->meetings;
		//$allMeetings =  $this->meeting->model->where('user_id','=',$id)->OrderBy('created_at','desc')->paginate(6);
		return View('site.meetings.inbox',compact('allMeetings'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

	function getShowMeeting($id){

		$meeting =  $this->meeting->model->find($id);
		return View('site.meetings.show',compact('meeting'));
	}

}

resources/views/site/meetings/create.blade.php
@extends('layouts._tow_col')

@section('styles')
    @parent
    <link rel="stylesheet" href="../css/bootstrap-timepicker.min.css"/>
    <link rel="stylesheet" href="http://davidstutz.github.io/bootstrap-multiselect/dist/css/bootstrap-multiselect.css"/>
@stop

@section('sub-content')
    @parent
    <h1>Create A Meeting</h1>


        @if($errors->has())
            <div class="alert alert-danger" role="alert">
            @foreach($errors->all() as $error)
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                {!! $error !!}</br>
            @endforeach
            </div>
        @endif



    {!! Form::open(['action'=>'MeetingController@store','Method'=>'post']) !!}
        <div class="form-group col-md-6">
            {!! Form::label('subject') !!}
                {!! Form::text('subject',null,['class'=>'form-control','placeholder'=>'Add a Subject']) !!}
        </div>
        <div class="col-md-6 form-group">
            {!! Form::label('date','Meeting Date : ') !!}
            {!! Form::date('date',Carbon\Carbon::now(), ['class'=>'form-control']) !!}
        </div>
    <div class="col-md-6 form-group">
        {!! Form::textarea('description',null,['class'=>'form-control','placeholder'=>'Description']) !!}
    </div>
        <div class="form-group col-md-6">
            {!! Form::label('Attendees :') !!}
            {!! Form::select('attendees',$allAttendees,null,['multiple'=>'multiple','name'=>'attendees[]','class'=>'form-control','placeholder'=>'Add a Subject','id'=>'attendee']) !!}
        </div>
        <div class="col-md-6 form-group">
            {!! Form::label('timepicker1', 'Meeting Time :') !!}
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1">@</span>
                   {{-- <input id="timepicker1" type="text" name="time" class="input-small form-control">--}}
                    {!! Form::text('time',null,['class'=>'input-small form-control','id'=>'timepicker1'])!!}
                </div>
        </div>



        <div class="col-md-12 form-group">
            {!! Form::hidden('user_id', Auth::user()->id) !!}
            {!! Form::submit('submit',['class'=>'btn btn-primary']) !!}
        </div>

    {!! Form::close() !!}
@stop

@section('scripts')
    @parent
    <script type="javascript" src="http://davidstutz.github.io/bootstrap-multiselect/dist/css/bootstrap-multiselect.css"></script>
    <script>
        $('#timepicker1').timepicker();

    </script>
@stop

resources/views/site/meetings/inbox.blade.php
@extends('layouts._tow_col')


@section('sub-content')
    @parent
    <div class="row">
        <div class="col-lg-12 col-md-12"><h1>Invitations</h1></div>
        @if(count($allMeetings) > 0)
            @foreach($allMeetings as $meeting)
                <div class="col-lg-12 col-md-12" style="">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4>{!! link_to_action('MeetingController@getShowMeeting',$meeting->subject,$meeting->id,null) !!}</h4>
                            </div>
                            <div class="panel-body">
                                <div class="col-lg-4 col-md-4">
                                    <a href="#">
                                        <img class="img-responsive" alt="Bootstrap template" src="http://loremicon.com/i/flat/64/computer">
                                    </a>
                                </div>
                                <div class="col-lg-8 col-md-8">
                                    <p class="text-justify">
                                        {!! str_limit($meeting->description, $limit = 80, link_to_action('MeetingController@getShowMeeting','..more',$meeting->id,null)) !!}
                                    </p>
                                    <div class="text-left">
                                        <a href="{!! route('meeting.create') !!}"><span class="glyphicon glyphicon-time"></span> {!! date('d-m-Y', strtotime(Carbon\Carbon::now()->now()->subDays($meeting->id*2))) !!}  </a>
                                        <a href="#"><span class="glyphicon glyphicon-hourglass"></span> {!! date('H:i', strtotime(Carbon\Carbon::now()->now()->subHours($meeting->id*3))) !!}</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

            @endforeach
        @else
            <div class="alert alert-info" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only"></span>
                No Meetings Invitations !!!!</br>
            </div>

        @endif
    </div>
@stop

resources/views/site/meetings/index.blade.php
@extends('layouts._tow_col')


@section('sub-content')
    @parent
    <div class="row">
        @if(count($allMeetings) > 0)
            @foreach($allMeetings as $meeting)
                {{--TOW MEETINGS WITHIN ONE ROW --}}
                <div class="col-lg-12 col-md-12" style="">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4>{!! link_to_action('MeetingController@getShowMeeting',$meeting->subject,$meeting->id,null) !!}</h4>
                            </div>
                            <div class="panel-body">
                                <div class="col-lg-4 col-md-4">
                                    <a href="#">
                                        <img class="img-responsive" alt="Bootstrap template" src="http://loremicon.com/i/flat/64/computer">
                                    </a>
                                </div>
                                <div class="col-lg-8 col-md-8">
                                    <p class="text-justify">
                                        {!! str_limit($meeting->description, $limit = 80, link_to_action('MeetingController@getShowMeeting','..more',$meeting->id,null)) !!}
                                    </p>
                                    <div class="text-left">
                                        <a href="{!! route('meeting.create') !!}"><span class="glyphicon glyphicon-time"></span> {!! date('d-m-Y', strtotime(Carbon\Carbon::now()->now()->subDays($meeting->id*2))) !!}  </a>
                                        <a href="#"><span class="glyphicon glyphicon-hourglass"></span> {!! date('H:i', strtotime(Carbon\Carbon::now()->now()->subHours($meeting->id*3))) !!}</a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

            @endforeach
        @else
            <div class="alert alert-info" role="alert">
                <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
                <span class="sr-only"></span>
                No Meetings available !!!!</br>
            </div>

        @endif

    </div>
    {!! $allMeetings->render() !!}
@stop

resources/views/site/meetings/show.blade.php
@extends('layouts._tow_col')


@section('sub-content')
    @parent
    <div class="row">

            {{--TOW MEETINGS WITHIN ONE ROW --}}
            <div class="col-lg-12 col-md-12" style="">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3>{!! $meeting->subject !!}</h3>
                    </div>
                    <div class="panel-body">
                        <div class="col-lg-4 col-md-4">
                            <a href="#">
                                <img class="img-responsive" alt="Bootstrap template" src="http://loremicon.com/i/flat/128/computer">
                            </a>
                        </div>
                        <div class="col-lg-8 col-md-8">
                            <p class="text-justify">
                                {!! $meeting->description !!}
                            </p>
                            <div class="text-left">
                                <span class="glyphicon glyphicon-time"></span> {!! date('d-m-Y', strtotime(Carbon\Carbon::now()->now()->subDays($meeting->id*2))) !!}
                                <span class="glyphicon glyphicon-hourglass"></span> {!! date('H:i', strtotime(Carbon\Carbon::now()->now()->subHours($meeting->id*3))) !!}
                            </div>
                        </div>

                    </div>
                </div>

            </div>


    </div>

@stop